### PR TITLE
Adding capability for packer_fmt to interpret options

### PR DESCRIPTION
**Pull request by nandac**
Adding capability for packer_fmt.sh handle packer command options
#  #

## 🗣 Description ##

The packer_fmt.sh script could not handle packer options such as `-write=true`, `-recursive` etc. as it was interpreting them as files instead of being options given to the packer command.

This change filters out the packer options from the files by checking if the argument starts with a hyphen (-). If it starts with a hyphen it is a packer option otherwise it is a file.

Of course, if a filename starts with a hyphen it will be treated as an option and it is on the user's shoulders to name the file correctly to work with this hook.

## 🧪 Testing ##

The code was tested with a sample test file test.pkr.hcl likes this:
```yaml
packer {
  required_plugins {
    amazon = {
      version = "~> 1.0"
      source  = "github.com/hashicorp/amazon"
    }
  }
}
```

Changes were made manually to this file for various cases and the following commands were tested:
.`/packer_fmt.sh test.pkr.hcl`
`./packer_fmt.sh -write=true test.pkr.hcl`
`./packer_fmt.sh -write=true -recursive test.pkr.hcl`
`./packer_fmt.sh -write=true -recursive -check test.pkr.hcl`
`./packer_fmt.sh -write=true -diff test.pkr.hcl`
`./packer_fmt.sh -write=true -stuff test.pkr.hcl`

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Add a tag or create a release.

### CODE REVIEW

**Comment by nlamirault** [comment]
Works fine ... thanks @nandac 
@jsf9k @mcdonnnj do you think you can create a new release with this patch ?

**Comment by nandac** [comment]
> Works fine ... thanks @nandac @jsf9k @mcdonnnj do you think you can create a new release with this patch ?

Thanks for reviewing looks like my branch was out of date so I updated it on the UI but it needs a maintainer to run the workflow.

**Comment by nandac** [comment]
@mcdonnnj @nlamirault @jsf9k Kindly let me know if I could help in any way to get a new release done with this patch. This PR has been open for several months.

**Comment by mcdonnnj** [comment]
@nandac I apologize for the radio silence. Unfortunately a lot of pressing work and I haven't had a chance to circle back to this on my off time. Although I appreciate the intent of this PR I would prefer an implementation along the lines of how [pre-commit-terraform processes command line arguments](https://github.com/antonbabenko/pre-commit-terraform/blob/080ce62dbcaafb56f45a8ca9b16813fad61becaa/hooks/_common.sh#L36-L97) to allow options to be passed to the hook in addition to options for the underlying program call. Off the top of my head this PR effectively makes implementing #13 with a command line switch to toggle behavior more unwieldy than I'd like. Let me think on it this weekend (and reference my future work notes and any local testing code I have) and get back to you Monday. I want to tentatively say that we'll probably just ship this as it is and unwind things in a later PR to get the desired functionality but I want to make sure I haven't forgotten something. It's been a bit since I really touched on this code actively.

**Comment by nandac** [comment]
@mcdonnnj Thank you for your response. I am all for improving this PR for the better. I would rather have it done well now than later so it does not need to be revisited for a while at least.

I will look at the code example you have provided a look into how I can improve this PR.

**Comment by mcdonnnj** [comment]
> @mcdonnnj Thank you for your response. I am all for improving this PR for the better. I would rather have it done well now than later so it does not need to be revisited for a while at least.
> 
> I will look at the code example you have provided a look into how I can improve this PR.

It does not need to be as complex/robust as the sample I linked. My main focus/concern is the mapping of specific options to underlying Packer options so that you can provide arguments to modify the hook's behavior as well.

**Comment by mcdonnnj** [comment]
As mentioned in https://github.com/cisagov/pre-commit-packer/pull/37 this functionality has been implemented in a separate PR.

**Pull request closed without merging**
